name: Build sdk

on:
  repository_dispatch:
    types: [build-sdk]

jobs:
  prepare:
    name: Prepare sdk build
    runs-on: ubuntu-latest
    outputs:
      build-date: ${{ steps.vars.outputs.date }}
      entware-ref: ${{ steps.vars.outputs.ref }}
      entware-arches: ${{ steps.vars.outputs.arches }}
    steps:
      - name: Checkout Entware
        uses: actions/checkout@v6
        with:
          repository: Entware/Entware

      - id: vars
        name: Write job values
        run: |
          ARCHERS=$(python3 -c 'from pathlib import Path; print([filename.stem for filename in Path("configs").iterdir()])')
          echo "arches=$ARCHERS" >> "$GITHUB_OUTPUT"
          echo "ref=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

  build:
    name: Build sdk ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(needs.prepare.outputs.entware-arches) }}
    env:
      DOCKER_IMAGE: ghcr.io/openwrt/buildbot/buildworker-v3.11.3:latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v6

      - name: Checkout Entware
        uses: actions/checkout@v6
        with:
          repository: Entware/Entware
          ref: ${{needs.prepare.outputs.entware-ref}}
          path: entware

      - name: Aplly patches to build sdk
        run: git apply $GITHUB_WORKSPACE/*.patch
        working-directory: entware

      - name: Pull builder docker image
        run: docker pull $DOCKER_IMAGE

      - name: Temporary change rights for GITHUB_WORKSPACE/entware
        run: sudo chown -R 1000:1000 $GITHUB_WORKSPACE/entware
        shell: bash

      - name: Build entware sdk ${{ matrix.arch }}
        run: >-
          docker run --rm
          -v $GITHUB_WORKSPACE/build_sdk.sh:/bin/build_sdk:ro
          -v $GITHUB_WORKSPACE/entware:/builder/entware
          -w /builder/entware
          $DOCKER_IMAGE
          /bin/build_sdk ${{ matrix.arch }}

      - name: Restore rights for $GITHUB_WORKSPACE/entware
        run: sudo chown -R --reference=$GITHUB_WORKSPACE $GITHUB_WORKSPACE/entware
        shell: bash
        if: always()

      - name: Upload asset to release
        uses: actions/upload-artifact@v7
        with:
          name: sdk-${{ matrix.arch }}
          path: entware/bin/targets/${{ matrix.arch }}/*/entware-sdk-${{ matrix.arch }}*
          if-no-files-found: error

  release:
    name: Upload release
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true

      - name: Update LastBuildRef.txt
        run: echo "${{ needs.prepare.outputs.entware-ref }}" > LastBuildRef.txt

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[auto] Build sdk ${{ needs.prepare.outputs.build-date }}"
          tag_name: 'v${{ needs.prepare.outputs.build-date }}'

      - uses: actions/download-artifact@v8

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: sdk-*/*
          tag_name: 'v${{ needs.prepare.outputs.build-date }}'
          fail_on_unmatched_files: true
