name: Periodically check Entware changes

on:
  schedule:
    # every 2nd saturday at 23:00 UTC
    - cron: "0 23 8-14 * 6"
  workflow_dispatch:

jobs:
  check:
    name: Check entware changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Entware
        uses: actions/checkout@v6
        with:
          repository: Entware/Entware
          path: entware

      - name: Checkout LastBuildRef.txt
        uses: actions/checkout@v6
        with:
          sparse-checkout: LastBuildRef.txt
          sparse-checkout-cone-mode: false
          path: self

      - id: vars
        name: Read current Entware ref
        run: |
          LAST_REF=$(cat self/LastBuildRef.txt 2>/dev/null || echo '')
          REF=$(cd entware; git rev-parse HEAD)
          echo "last-ref=$LAST_REF" >> "$GITHUB_OUTPUT"
          echo "ref=$REF" >> "$GITHUB_OUTPUT"

      - name: Triggger build sdk
        if: ${{ steps.vars.outputs.last-ref != steps.vars.outputs.ref }}
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: build-sdk
